In [2]:
import pandas as pd
print("hello")

hello

In [4]:
import os
print(os.getcwd())

/home/sanjeev/f110_ws/src/Data

In [12]:
df = pd.read_csv("../training_data_overtakemap.csv")

In [13]:
df.head(5)

        d_m  heading_error     kappa        vx  kappa_lookahead  steering
0 -0.030418      -0.036509 -0.176642  4.757382        -0.149549 -0.100000
1 -0.040085      -0.028490 -0.174187  4.778383        -0.148079 -0.100000
2 -0.026348      -0.037915 -0.174187  4.799007        -0.148079 -0.100000
3 -0.041088      -0.030835 -0.170672  4.819503        -0.147920 -0.113592
4 -0.022732      -0.040463 -0.170672  4.840478        -0.147920 -0.113592

In [17]:
df.shape

(24338, 6)

In [14]:
df_2 = pd.read_csv("../training_data_f.csv")

In [15]:
df_2.head(5)

        d_m  heading_error     kappa        vx  kappa_lookahead  steering
0 -0.025997      -0.079904 -0.434465  3.563410        -0.308278 -0.141379
1 -0.043063      -0.094562 -0.434465  3.568955        -0.308278 -0.141379
2 -0.038051      -0.066168 -0.418932  3.574373        -0.298100 -0.141379
3 -0.025483      -0.079458 -0.418932  3.579683        -0.298100 -0.141379
4 -0.049460      -0.092621 -0.418932  3.584882        -0.298100 -0.131034

In [18]:
df_2.shape

(12650, 6)